---
- name: Install Packages on Target Server
  hosts: all
  become: yes
  tasks:
    - name: Install apache2 package
      ansible.builtin.package:
        name: apache2
        state: present

    - name: Start the apache2 service
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

